---
title: "HCR Exploration"
author: "JGaun"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
library(plotly)
library(patchwork)
```


#### Load the Data

Data from Erin January 2022

```{r load data and create factor levels for sites}
hcr_trends <- read_csv(here("data", "HCR_SummarizedResultsFinal_Jan2022.csv"))

#order sites from upstream to downstream
hcr_trends$siteName <- as.factor(hcr_trends$siteName)

factor(hcr_trends$siteName, levels = c("Pool4A", "Pool4B", "Pool5_6", "Pool8", "LD9", "LD11", "Pool13", "LD15", "LD17", "LD19", "LD21", "LD24", "Pool26", "OpenRiver", "J-36", "I-05", "LaGrange" ))

factor(hcr_trends$cTrendConfidence, levels = c("low", "moderate", "high"))

hcr_trends <- hcr_trends %>% 
  mutate(siteName = fct_relevel(siteName,"Pool4A", "Pool4B", "Pool5_6", "Pool8", "LD9", "LD11", "Pool13", "LD15", "LD17", "LD19", "LD21", "LD24", "Pool26", "OpenRiver", "J-36", "I-05", "LaGrange")) %>% 
  mutate(cTrendConfidence = fct_relevel(cTrendConfidence, "low", "moderate", "high"))


head(hcr_trends)
```

```{r chloride}
#all chloride trends
chloride<- hcr_trends %>% 
  filter(parameter == "Chloride") %>%
  select(siteName, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) 

#hgh confidence chloride trends
chloride_high <- hcr_trends %>% 
  filter(parameter == "Chloride") %>%
  select(siteName, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) %>% 
  filter(cTrendConfidence =="high") 


#plot chloride trends
ggplot(chloride, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Chloride Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

#summary high confidence chloride trends
summary(chloride_high$cPercentChangeTotal)
summary(chloride_high$cAmtChangeTotal)

#summary all chloride trends
summary(chloride$cPercentChangeTotal)
summary(chloride$cAmtChangeTotal)

```

```{r sulfate}
sulfate<- hcr_trends %>% 
  filter(parameter == "Sulfate") %>%
  select(siteName, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) 

#hgh confidence chloride trends
sulfate_high <- hcr_trends %>% 
  filter(parameter == "Sulfate") %>%
  select(siteName, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) %>% 
  filter(cTrendConfidence =="high") 


#plot chloride trends
ggplot(sulfate, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Sulfate Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

#summary high confidence chloride trends
summary(sulfate_high$cPercentChangeTotal)
summary(sulfate_high$cAmtChangeTotal)

#summary all chloride trends
summary(sulfate$cPercentChangeTotal)
summary(sulfate$cAmtChangeTotal)
```

#### Nutrients
```{r nutrients}
 #all nutrient trends
nutrients<- hcr_trends %>% 
  filter(parameter == "Total Phosphorus"|
         parameter == "Total Nitrogen"|
         parameter == "Inorganic Nitrogen"|
         parameter == "Ammonia"|
         parameter == "Chlorophyll-a") %>%
  select(siteName, parameter, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence)

#all nutrients by site
ggplot(nutrients, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  facet_wrap(~parameter, ncol = 3)+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 90, size = 6))+
  labs(title = "Total Nitrogen Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")



#Nitrogen 
nitrogen_all <- nutrients %>% 
  filter(parameter == "Total Nitrogen"|
         parameter == "Inorganic Nitrogen"|
         parameter == "Ammonia")

##Total Nitrogen
total_n<- nutrients %>% 
  filter(parameter == "Total Nitrogen")

ggplot(total_n, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Nitrogen Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

tn_high <- total_n %>%
  filter(cTrendConfidence =="high")

## Inorganic Nitrogen 
inorg_n <- nutrients %>% 
  filter(parameter == "Inorganic Nitrogen")

ggplot(inorg_n, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Inorganic Nitrogen Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

inorg_n_high <- inorg_n %>%
  filter(cTrendConfidence =="high")

## Chlorophyll-a
chl<- nutrients %>% 
  filter(parameter == "Chlorophyll-a")

ggplot(chl, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Chlorophyll-a Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

chl_high <- chl %>%
  filter(cTrendConfidence =="high") 

##Total Phosphorus 
t_phos <- nutrients %>% 
  filter(parameter == "Total Phosphorus") %>% 
  na.omit()
  

ggplot(t_phos, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Phosphorus Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

t_phos_high <- t_phos %>% 
  filter(cTrendConfidence == "high") %>% 
  filter(siteName != "Pool26")

ggplot(t_phos_high, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Phosphorus Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

summary(t_phos_high$cPercentChangeTotal)

```

```{r ammonia}
##Ammonia 
ammonia <- nutrients %>% 
  filter(parameter == "Ammonia")

ggplot(ammonia, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-150, 150))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Ammonia Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

###high confidence ammonia trends
ammonia_high <- ammonia %>%
  filter(cTrendConfidence =="high")

summary(ammonia_high$cPercentChangeTotal)
summary(ammonia_high$cAmtChangeTotal)
```

```{r metals}
 #all nutrient trends
metals<- hcr_trends %>% 
  filter(parameter == "Total Aluminum"|
         parameter == "Total Arsenic"|
         parameter == "Total Copper"|
         parameter == "Total Cadmium"|
         parameter == "Total Lead" |
         parameter == "Total Mercury") %>%
  select(siteName, parameter, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) 

factor(metals$siteName, levels = c("Pool4A", "Pool4B", "Pool5_6", "Pool8", "LD9", "LD11", "Pool13", "LD15", "LD17", "LD19", "LD21", "LD24", "Pool26", "OpenRiver", "J-36", "I-05", "LaGrange" ))

#Aluminum 
metal_al<- metals%>% 
  filter(parameter == "Total Aluminum")
ggplot(metal_al, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Aluminum Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

##Total Arsenic
metal_ar <- metals%>% 
  filter(parameter == "Total Arsenic")

ggplot(metal_ar, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Arsenic Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

## Total Copper
metal_cu<-metals%>% 
  filter(parameter == "Total Copper")

ggplot(metal_cu, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 100))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Copper Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

## Total Cadmium
metal_cd<-metals%>% 
  filter(parameter == "Total Cadmium")

## Total Lead
metal_pb<-metals%>% 
  filter(parameter == "Total Lead")

ggplot(metal_pb, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-450, 450))+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Lead Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")


## Total Mercury
metal_hg <-  metals%>% 
  filter(parameter == "Total Mercury")

```


```{r TSS}
tss <- hcr_trends %>% 
  filter(parameter == "Total Suspended Solids")%>%
  select(siteName, parameter, timePeriod, cDirection, cPercentChangeTotal, cAmtChangeTotal, cUnits, cTrendConfidence) 

summary(tss$cPercentChangeTotal)
summary(tss$cAmtChangeTotal)

tss_high <- tss %>% 
  filter(cTrendConfidence == "high")

summary(tss_high$cPercentChangeTotal)
summary(tss_high$cAmtChangeTotal)

ggplot(tss, aes(x =siteName, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  scale_y_continuous(limits= c(-100, 100))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  theme(axis.text.x = element_text(angle= 45))+
  labs(title = "Total Suspended Solids Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")

```

```{r LD15}
ld_15 <- hcr_trends %>% 
  filter(siteName == "LD15")

#all nutrients by site
ggplot(ld_15, aes(x =parameter, y =cPercentChangeTotal))+
  geom_point(aes(color= cTrendConfidence))+
  scale_color_manual(values=c("#999999", "#56B4E9", "#E69F00"))+
  geom_hline(yintercept = 0, size =.25, color = "black")+
  scale_y_continuous(limits = c(-100, 500))+
  theme(axis.text.x = element_text(angle= 90, size = 6))+
  labs(title = "Total Nitrogen Percent Change in Concentration",
       y = "Percent Change in Concentration",
       x = "Site")
  
```



